### ISSUE TITLE
(Fix) Change logo to POA

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/oracles-dapps-keys-generation#31]
Problem: DApp uses old logo 
Solution: Use new logo
[Archive 2.zip](https://github.com/oraclesorg/poa-dapps-keys-generation/files/1561064/Archive.2.zip)

**Comment by vbaranov** [comment]
The same problem, as here https://github.com/oraclesorg/poa-dapps-validators/issues/9#issuecomment-351923960. New footer images are absent. Current: [Archive.zip](https://github.com/oraclesorg/poa-dapps-keys-generation/files/1561754/Archive.zip)

**Comment by igorbarinov** [comment]
[Archive 4.zip](https://github.com/oraclesorg/poa-dapps-keys-generation/files/1562979/Archive.4.zip)

**Comment by vbaranov** [comment]
Implemented here: https://github.com/oraclesorg/poa-dapps-keys-generation/pull/32
