### ISSUE TITLE
Method for saving keys & passwords

### ISSUE THREAD

**Issue by hashguide** [oraclesorg/oracles-dapps-keys-generation#60]
People tend to forget to save the passwords required for mining keys, it could be a good idea to provide compressed files including the keys and text file of passwords and possibly password protecting the compressed file.

**Comment by igorbarinov** [comment]
Let's discuss how to make it secure and UX firendly

**Comment by johnnynuuma** [comment]
I have mixed feelings about the "one download" solution and don't have any good ideas currently that are both secure and UX friendly.   The benefits of the current model is that it takes time, patience and organized thought to download and secure (3) keys so a vetting challenge for Validators to some degree.
