### ISSUE TITLE
Rename mining key to something else ( validating key or signing key )

### ISSUE THREAD

**Issue by johnnynuuma** [oraclesorg/oracles-dapps-keys-generation#61]
Since we don't mine in our network, the use of mining key is a misnomer and should settle on a different name for "mining key"  in key generation, documentation and deployment variables for consistency.

**Comment by igorbarinov** [comment]
From "Blockchain 101: Cryptoeconomic Primitives and Staking" on https://www.zeroknowledge.fm/49

00:39:27

Anna Rose: You were mentioning miners not validators. Why were you saying that?

Axel Ericsson: Sorry I was just using the terms interchangeably. I think miners is a pretty neat sort of broad term. All different systems use different terms for their proof of stake miners so it could be staker or validator or even baker and Tezos for some reason. So we have all of these different terms.
