### ISSUE TITLE
Generate Keys button does not work

### ISSUE THREAD

**Issue by wandergeek** [oraclesorg/oracles-dapps-keys-generation#73]
Hello,

For some reason my instance of this project is not allowing me to click the 'Generate Keys' button.  These steps are all derived from this document: https://github.com/poanetwork/wiki/wiki/Master-of-Ceremony-Setup. Here are the specific steps I've taken:

1) Generate initial keys using `poa-scritps/generateInitialKey`
2) Edit `src/getWeb3.js` and add an entry for my network:
```
 case "26936":
	      netIdName = 'mynet'
   	      console.log('this is my net')
	      break
```
3) Edit `src/keysManager.js` and change KEYS_MANAGER_ADDRESS to reflect the key manager address generated from `poa-network-consensus-contracts`.

I see the following error in the console:
```
index.js:2177 Warning: Invalid DOM property `class`. Did you mean `className`?
    in a (at Header.js:8)
    in div (at Header.js:7)
    in header (at Header.js:6)
    in Header (at App.js:197)
    in div (at App.js:196)
    in App (at index.js:8)
```

I've managed to get rid of this error by editing Header.js and changing appropriate fields to className, however the generate initial keys button is still inactive.

Cheers

**Comment by varasev** [comment]
Hi @wandergeek

Could you show your `keysManager.js` code and browser's console here?

**Comment by vbaranov** [comment]
@wandergeek also
- is Metamask installed?
- are you logged into it?
- is correct initial key unlocked in Metamask?
- are you connected in Metamask to the right network?

**Comment by varasev** [comment]
> I see the following error in the console: ...

I renamed `class` to `className` in https://github.com/poanetwork/poa-dapps-keys-generation/pull/74.

**Comment by vbaranov** [comment]
@wandergeek does problem still exist for you?

**Comment by wandergeek** [comment]
I managed to sort this out. Issue was related to metamask. 

Cheers,
Nick
