### ISSUE TITLE
Change design to new style

### ISSUE THREAD

**Issue by pashagonchar** [oraclesorg/oracles-dapps-keys-generation#79]
**Zeplin:** https://zpl.io/bAEWLrp  https://zpl.io/2pBkE5E
![poa_ceremony_app](https://user-images.githubusercontent.com/16716926/44796735-50098980-abb6-11e8-8d5b-f605a249d321.png)
![poa_ceremony_app_2](https://user-images.githubusercontent.com/16716926/44796749-57309780-abb6-11e8-9aac-c5daca0df134.png)

**Comment by varasev** [comment]
Hi @gabitoesmiapodo,

we have new layouts for Ceremony DApp (see above).

**Comment by gabitoesmiapodo** [comment]
@varasev OK, I was told by @pablofullana 

Will be done in the upcoming days / weeks (already working on some POA Network projects).

**Comment by igorbarinov** [comment]
@pablofullana please prioritize it since we discontinued TokenWizard https://medium.com/poa-network/farewell-token-wizard-2-0-time-to-reprioritize-8cbd7319a97b and prioritizing other tasks for Gabriel

@pashagonchar the design should show on which network we are

**Comment by gabitoesmiapodo** [comment]
Hi @igorbarinov @pashagonchar 

These are the things I think we may be missing for this DApp's new styles implementation:

- Sokol version (colors, logo, etc.).
- Responsive versions would be nice (if not, I'll handle it).

I'm currently working on the POA landing page (some xDai's page fixes, and the new Bridge section's design), and will continue with it unless this has higher priority.

**Comment by gabitoesmiapodo** [comment]
I've started working on this issue.

**Comment by pashagonchar** [comment]
Small update

![poa_ceremony_app](https://user-images.githubusercontent.com/16716926/49696066-1aa90a80-fbad-11e8-9867-e9dc3bb6890c.png)
![sokol_ceremony_app](https://user-images.githubusercontent.com/16716926/49696067-1aa90a80-fbad-11e8-84da-0557fdf1ea36.png)
![xdai_ceremony_app](https://user-images.githubusercontent.com/16716926/49696068-1aa90a80-fbad-11e8-8fe7-a628229a3652.png)

**Comment by gabitoesmiapodo** [comment]
@pashagonchar Got it.

**Comment by gabitoesmiapodo** [comment]
@pashagonchar can you update the Zeplin project so I can grab the logos, styles, etc.?

**Comment by pashagonchar** [comment]
@gabitoesmiapodo yes, I'll finish and update zeplin

**Comment by pashagonchar** [comment]
@gabitoesmiapodo 
Update

![poa_ceremony_app_2](https://user-images.githubusercontent.com/16716926/49868696-de78e280-fe16-11e8-9fea-a08d0fe786d8.png)
![poa_ceremony_app](https://user-images.githubusercontent.com/16716926/49868698-df117900-fe16-11e8-88d7-d1f3171ef2af.png)
![sokol_ceremony_app_2](https://user-images.githubusercontent.com/16716926/49868700-df117900-fe16-11e8-9170-df432d385779.png)
![sokol_ceremony_app](https://user-images.githubusercontent.com/16716926/49868701-dfaa0f80-fe16-11e8-94d2-3deaf5e93757.png)
![xdai_ceremony_app_2](https://user-images.githubusercontent.com/16716926/49868702-dfaa0f80-fe16-11e8-8438-af4f470ce005.png)
![xdai_ceremony_app](https://user-images.githubusercontent.com/16716926/49868703-dfaa0f80-fe16-11e8-9d78-4435e7992e50.png)

Zeplin

POA:

https://zpl.io/awWqX1D   

https://zpl.io/aMKdN9R

Sokol:

https://zpl.io/a3gXOKA

https://zpl.io/2jvZ9Pr

xdai:

https://zpl.io/a8plepw

https://zpl.io/2Zj07jE
